## IMPORTING

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error, r2_score

## Variables

X1 = Tanggal = 14 = 0.02 <br>
X2 = Bulan = 61 = 0.08<br>
X3 = Tahun = 25 = 0.03 <br>
X4 = Komoditas = 763 = 1 <br>
Y = Harga = -46285 = 60 <br>


## LOAD DATASET

In [ ]:
df = pd.read_csv('/content/DATASET KOMODITAS.csv')

## CHECKING MISSING VALUES

In [ ]:
df.head()

Hari  Tanggal  Bulan  Tahun  Komoditas  Harga
0     1        4      3   2024          1  11600
1     3       28      2   2024          1  11600
2     1       26      2   2024          1  11000
3     4       22      2   2024          1  11000
4     1       19      2   2024          1  11000

In [ ]:
df.isnull().sum()

Hari         0
Tanggal      0
Bulan        0
Tahun        0
Komoditas    0
Harga        0
dtype: int64

In [ ]:
print(df.shape)

(24604, 6)


In [ ]:
df['Komoditas'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77])

## TRAINING

In [ ]:
features = df[['Tanggal','Bulan','Tahun','Komoditas']]
target = df[['Harga']]

In [ ]:
features

Hari  Tanggal  Bulan  Tahun  Komoditas
0         1        4      3   2024          1
1         3       28      2   2024          1
2         1       26      2   2024          1
3         4       22      2   2024          1
4         1       19      2   2024          1
...     ...      ...    ...    ...        ...
24599     5       11     11   2022         77
24600     4       10     11   2022         77
24601     1        7     11   2022         77
24602     5        4     11   2022         77
24603     1       31     10   2022         77

[24604 rows x 5 columns]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(features,target,test_size=0.33, random_state=0)

In [ ]:
reg = LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred = reg.predict(x_test)
print(y_pred)

[[17388.5351336 ]
 [23993.91525534]
 [ 9490.94171414]
 ...
 [39641.22448334]
 [58003.64664028]
 [22919.70402365]]


In [ ]:
reg.coef_

array([[ 14.01209952,  61.65223265,  25.63954386, 763.56541324]])

In [ ]:
reg.intercept_

array([-46285.59089166])

## EVALUATE THE RESULT

In [ ]:
r2 = r2_score(y_test,y_pred)
print("R2 Score =", r2)
n = len(y_test)
p = 5
adjusted_r2 = (1 - r2) * (n - 1) / (n - p - 1)
print("Adjusted R2 Score = ", adjusted_r2)

R2 Score = 0.19666811561595976
Adjusted R2 Score =  0.8038269126588641


In [ ]:
print(y_pred.shape)

(8120, 1)


## SAVING MODEL

In [ ]:
import pickle
with open("rlinear.pkl", "wb") as f:
    pickle.dump(reg, f)

## TESTING WITH ANOTHER CSV FILE

In [ ]:
def predict(filepath):
  df_test = pd.read_csv(filepath)
  fin_res = reg.predict(df_test)
  omega = pd.DataFrame(fin_res)

In [ ]:
filepath = ("/content/test.csv")

In [ ]:
df_testing = pd.read_csv('/content/test.csv')
testing = reg.predict(df_testing)
print(testing)

[[6683.38415235]
 [6848.36397233]
 [6921.65986317]
 [6716.69491402]
 [6826.63875028]]


In [ ]:
test = reg.predict([[4,3,2023,1]])
print(test)

[[6587.77685149]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
